run:
  concurrency: 4
  deadline: 3m
  issues-exit-code: 1
  tests: true
output:
  format: colored-line-number

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: false
  gocyclo:
    min-complexity: 10
  lll:
    line-length: 120
    tab-width: 1
  dupl:
    threshold: 160

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl

linters:
  enable-all: true
