apiVersion: v1
kind: Service
metadata:
  name: {{ include "calc-api.fullname" . }}
  labels:
    {{- include "calc-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: UDP
      name: grpc
  selector:
    {{- include "calc-api.selectorLabels" . | nindent 4 }}
