name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out the code
        uses: actions/checkout@v1

      - name: Make lint
        run: make lint
        env:
          CI: 'true'
          VERBOSE: 'true'

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out the code
        uses: actions/checkout@v1

      - name: Make test
        run: make test
        env:
          CI: 'true'
          VERBOSE: 'true'

      - name: Test charts
        run: |
          sudo rm /usr/local/bin/helm
          make lint-all-charts -B

  build:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out the code
        uses: actions/checkout@v1

      - name: Make build
        run: make build-all -B
        env:
          CI: 'true'
          VERBOSE: 'true'

  kind:
    needs: build
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.3.0
    - name: 
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
